name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rector:
    uses: ./.github/workflows/rector-fix.yml
    secrets: inherit

  duster:
    needs: rector
    uses: ./.github/workflows/duster-fix-blame.yml
    secrets: inherit

  phpstan:
    needs: duster
    uses: ./.github/workflows/phpstan.yml
    secrets: inherit

  tests:
    needs: phpstan
    uses: ./.github/workflows/tests.yml
    secrets: inherit
